#!/bin/bash

set -xe

pwd
env

cf api $PAS_API --skip-ssl-validation

cf login -u $PAS_USER -p $PAS_PWD -o "$PAS_ORG" -s "$PAS_SPACE"

cf apps

set +e
cf apps | grep "main-$PAS_APP_SUFFIX" | grep green
if [ $? -eq 0 ]
then
  echo "green" > ./current-app-info/current-app.txt
  echo "blue" > ./current-app-info/next-app.txt
else
  echo "blue" > ./current-app-info/current-app.txt
  echo "green" > ./current-app-info/next-app.txt
fi
set -xe

echo "Current main app routes to app instance $(cat ./current-app-info/current-app.txt)"
echo "New version of app to be deployed to instance $(cat ./current-app-info/next-app.txt)"
