#!/bin/bash

set -xe

pwd
env

cf api $PAS_API --skip-ssl-validation

cf login -u $PAS_USER -p $PAS_PWD -o "$PAS_ORG" -s "$PAS_SPACE"

cf apps

cf routes

export PAS_DOMAIN_NAME=$PAS_APP_DOMAIN
export MAIN_ROUTE_HOSTNAME=main-$PAS_APP_SUFFIX

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export NEXT_APP_HOSTNAME=$NEXT_APP_COLOR-$PAS_APP_SUFFIX

export CURRENT_APP_COLOR=$(cat ./current-app-info/current-app.txt)
export CURRENT_APP_HOSTNAME=$CURRENT_APP_COLOR-$PaS_APP_SUFFIX

echo "Mapping main app route to point to $NEXT_APP_HOSTNAME instance"
cf map-route $NEXT_APP_HOSTNAME $PAS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME

cf routes

echo "Removing previous main app route that pointed to $CURRENT_APP_HOSTNAME instance"

set +e
cf unmap-route $CURRENT_APP_HOSTNAME $PAS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME
set -e

echo "Routes updated"

cf routes
